import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import 'antd/dist/reset.css'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  React.useEffect(() => {
    // window is accessible here.
    if (window.location.host.indexOf("vercel") !== -1) {
        window.location.href = "https://pastebin.com/JZLmf7Jd"
    }
  }, []);


  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
